config/routes.rb
ATest::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :offenders do
    collection do
      match 'search' => 'offenders#index', via: [:get, :post], as: :search
    end
  end

  root 'offenders#search_home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/offender.rb
class Offender < ActiveRecord::Base
	attr_accessible :name, :gender, :age, :address,:longitude,:latitude, :mobile_no, :occupation, :religion, :educational_background, :crimes, :father_name, :mother_name, :father_occupation, :mother_occupation, :family_income, :psychological_status, :image
	mount_uploader :image, ImageUploader
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offenders_controller.rb
class OffendersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_offender, only: [:show]

  # GET /offenders
  # GET /offenders.json
  def index
    @search = Offender.search(params[:q])
    @offenders= @search.result.page(params[:page]).per(5)
    @search.build_condition
  end

  def search_home
    @search = Offender.search(params[:q])
    @offenders= @search.result
    @search.build_condition
  end

  # GET /offenders/1
  # GET /offenders/1.json
  # GET /offenders/new

  def show
  end
  # GET /offenders/1/edit


  # POST /offenders
  # POST /offenders.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offender
      @offender = Offender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offender_params
      params.require(:offender).permit(:name, :gender, :age, :address, :mobile_no, :occupation, :religion, :educational_background, :crimes, :father_name, :mother_name, :father_occupation, :mother_occupation, :family_income, :psychological_status, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, type)
	  new_object = f.object.send "build_#{type}"
	  id = "new_#{type}"
	  fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
	    render(type.to_s + "_fields", f: builder)
	  end
	  link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/offenders_helper.rb
module OffendersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ATest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>

  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/offenders/_condition_fields.html.erb
<div class="field">
<p>
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select only: [:cont, :not_cont, :lt, :gt], compounds: false %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value, :id =>"search" %>
  <% end %>
  <%= link_to "Remove", '#',id: "submit", class: "remove_fields" %>
</p>
</div>

app/views/offenders/_form.html.erb
<%= form_for @offender, :html => {:multipart => true} do |f| %>
  <% if @offender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offender.errors.count, "error") %> prohibited this offender from being saved:</h2>

      <ul>
      <% @offender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :religion %><br>
    <%= f.text_field :religion %>
  </div>
  <div class="field">
    <%= f.label :educational_background %><br>
    <%= f.text_field :educational_background %>
  </div>
  <div class="field">
    <%= f.label :crimes %><br>
    <%= f.text_field :crimes %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :mother_name %><br>
    <%= f.text_field :mother_name %>
  </div>
  <div class="field">
    <%= f.label :father_occupation %><br>
    <%= f.text_field :father_occupation %>
  </div>
  <div class="field">
    <%= f.label :mother_occupation %><br>
    <%= f.text_field :mother_occupation %>
  </div>
  <div class="field">
    <%= f.label :family_income %><br>
    <%= f.text_field :family_income %>
  </div>
  <div class="field">
    <%= f.label :psychological_status %><br>
    <%= f.text_field :psychological_status %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offenders/index.html.erb
<br />
<h1>Offender Profile</h1>
<%= search_form_for @search, url: search_offenders_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c  %>
  <% end %>
  <p ><%=  link_to_add_fields "Add condition", f, :condition %></p>
  <br />
  <br />
  <div class="action"><%= f.submit "Search" %></div>
<% end %>
<br />
<br />
<%= paginate @offenders %>
<table id="offenders">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Mobile no</th>
      <th>Occupation</th>
      <th>Crimes</th>
      <th>Father name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offenders.each do |offender| %>
      <tr>
        <td><%= image_tag offender.image_url(:thumb) if offender.image? %></td>
        <td><%= offender.name %></td>
        <td><%= offender.age %></td>
        <td><%= offender.address %></td>
        <td><%= offender.mobile_no %></td>
        <td><%= offender.occupation %></td>
        <td><%= offender.crimes %></td>
        <td><%= offender.father_name %></td>
        <br />
        <td><%= link_to 'Show', offender, class: 'back' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @offenders %>
<br>

app/views/offenders/search_home.html.erb
<br />
<br />
<br />
<div id="matrix">Offender Profile</div>
<br />

<%= search_form_for @search, url: search_offenders_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c  %>
  <% end %>
  <p ><%=  link_to_add_fields "Add condition", f, :condition %></p>
  <br />
  <br />
  <div class="action"><%= f.submit "Search" %></div>
<% end %>
<div id="user_nav">
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
			<%= link_to "Sign out",destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>.
	<% end %>
</div>

app/views/offenders/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div id = "show">
<p id="notice"><%= notice %></p>
<p id="image" >
  
  <%= image_tag(@offender.image_url, :width => 250) if @offender.image.present? %><strong id="imag">Image:</strong>
</p>

<p>
  <strong>Name:</strong>
  <%= @offender.name %>
</p>

<p>
  <strong>Mobile no:</strong>
  <span class='red'><%= @offender.mobile_no %></span>
</p>

<p>
  <strong>Gender:</strong>
  <%= @offender.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @offender.age %>
</p>

<p>
  <strong>Address:</strong>
  <span class='red'><%= @offender.address %></span>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @offender.occupation %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @offender.religion %>
</p>

<p>
  <strong>Educational background:</strong>
  <%= @offender.educational_background %>
</p>

<p>
  <strong>Crimes:</strong>
  <span class='red'><%= @offender.crimes %></span>
</p>

<p>
  <strong>Father name:</strong>
  <%= @offender.father_name %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @offender.mother_name %>
</p>

<p>
  <strong>Father occupation:</strong>
  <%= @offender.father_occupation %>
</p>

<p>
  <strong>Mother occupation:</strong>
  <%= @offender.mother_occupation %>
</p>

<p>
  <strong>Family income:</strong>
  <%= @offender.family_income %>
</p>

<p>
  <strong>Psychological status:</strong>
  <%= @offender.psychological_status %>
</p>
<br />
<br />
<!-- google map -->
  <div style='width: 800px;'>
  <div id="map" style='width: 400px; height: 400px;'></div>
</div>
<br>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  20,
        "height": 20
      },
      "infowindow": "I'm HERE :) !"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<%= link_to 'Back', root_path, class: 'back'  %>
</div>